version: '3.6'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8090:8080'
    command: start-dev --import-realm
    volumes:
      - ./realms/export/:/opt/keycloak/data/import/
